INSERT INTO "curriculums" ("curriculum_id", "code", "program_id", "name", "type", "status", "acad_org", "acad_group", "created_at", "updated_at", "is_visible", "course_work_guide", "approved_by", "date_approved") VALUES 
(47, 'BACA_2018_SPCM', 4, 'BACA 2018 Speech Communication', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(2, 'BSA_2018_ANSC_MPSP', 1, 'BSA 2018 Animal Science (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(48, 'BACA_2018_THEA', 4, 'BACA 2018 Theatre Arts', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(1, 'BSA_2018_ANSC_THPR', 1, 'BSA 2018 Animal Science (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(92, 'BSCE_2018_THESIS', 22, 'BSCE 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(112, 'BSIE_2018_THESIS', 24, 'BSIE 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(137, 'BSHE_2018_SOCIAL TECHNOLOGY (ST)', 26, 'BSHE 2018 Social Technology (ST)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(139, 'BSN_2018', 27, 'BSN 2018', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(140, 'DVM_2018', 28, 'DVM 2018', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(85, 'BSABE_2018_AMPE_ENGINEERING_INDUSTRY_RESEARCH', 20, 'BSABE 2018 Agribiosystems Machinery Power Engineering Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(107, 'BSEE_2018_COMPUTER_ENGINEERING_INNOVATIONEERING', 23, 'BSEE 2018 Computer Engineering Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(108, 'BSEE_2018_COMPUTER_ENGINEERING_ENGINEERING_INDUSTRY_RESEARCH', 23, 'BSEE 2018 Computer Engineering Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(109, 'BSEE_2018_ELECTRONICS_ENGINEERING_THESIS', 23, 'BSEE 2018 Electronics Engineering Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(91, 'BSABE_2018_LWRE_ENGINEERING_INDUSTRY_RESEARCH', 20, 'BSABE 2018 Land and Water Resources Engineering Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(99, 'BSChE_2018_SUGAR_TECHNOLOGY_ENGINEERING_INDUSTRY_RESEARCH', 21, 'BSChE 2018 Sugar Technology Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(101, 'BSChE_2018_PULP_AND_PAPER_INNOVATIONEERING', 21, 'BSChE 2018 Pulp and Paper Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(102, 'BSChE_2018_PULP_AND_PAPER_ENGINEERING_INDUSTRY_RESEARCH', 21, 'BSChE 2018 Pulp and Paper Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(159, 'BSCHE_2018_CHEMICAL_ENGINEERING_BASE', 21, 'BSCHE 2018 General Track', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(111, 'BSEE_2018_ELECTRONICS_ENGINEERING_INDUSTRY_RESEARCH', 23, 'BSEE 2018 Electronics Engineering Engineering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(104, 'BSEE_2018_POWER_INNOVATIONEERING', 23, 'BSEE 2018 Power Engineering Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(143, 'BSFST_2018_GENERAL', 3, 'BSFST 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(146, 'BASOC_2018_GENERAL', 6, 'BASOC 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(149, 'BSBIO_2018_GENERAL', 9, 'BSBIO 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(152, 'BSCHEM_2018_GENERAL', 10, 'BSCHEM 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(94, 'BSChE_2018_GENERAL_THESIS', 21, 'BSChE 2018 General Thesis', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(95, 'BSChE_2018_GENERAL_INNOVATIONEERING', 21, 'BSChE 2018 General Innovationeering', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(141, 'BSA_2018_GENERAL', 1, 'BSA 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(142, 'BSABT_2018_GENERAL', 2, 'BSABT 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(90, 'BSABE_2018_LWRE_INNOVATIONEERING', 20, 'BSABE 2018 Land and Water Resources Engineering Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(116, 'BSME_2018_INNOVATIONEERING', 29, 'BSME 2018 Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(4, 'BSA_2018_AGR_CRP_PROD_MGMT_THPR', 1, 'BSA 2018 Agriculture Crop Production Manangement (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(7, 'BSA_2018_AGR_CRP_PROD_MGMT_MPSP', 1, 'BSA 2018 Agriculture Crop Production Manangement (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(9, 'BSA_2018_HORT_LANDSCAPE_THPR', 1, 'BSA 2018 Horticulture Landscape (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(10, 'BSA_2018_HORT_CPM_VEG_THPR', 1, 'BSA 2018 Horticulture Crop Production Management Vegtables (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(13, 'BSA_2018_HORT_PH_THPR', 1, 'BSA 2018 Horticulture Postharvest (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(14, 'BSA_2018_HORT_PHYSIO_TISSUE_CULTURE', 1, 'BSA 2018 Horticulture Physiology Tissue Culture', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(16, 'BSA_2018_HORT_LANDSCAPE_MPSP', 1, 'BSA 2018 Horticulture Landscape (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(19, 'BSA_2018_HORT_CPM_FRUITS_MPSP', 1, 'BSA 2018 Horticulture Crop Production Management Fruits (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(20, 'BSA_2018_HORT_PH_MPSP', 1, 'BSA 2018 Horticulture Postharvest (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(23, 'BSA_2018_ENT_THPR', 1, 'BSA 2018 Entomology (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(24, 'BSA_2018_ENT_MPSP', 1, 'BSA 2018 Entomology (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(26, 'BSA_2018_PPTH_MPSP', 1, 'BSA 2018 Plant Pathology (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(28, 'BSA_2018_WEEDS_MPSP', 1, 'BSA 2018 Weeds (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(31, 'BSA_2018_SOIL_THPR', 1, 'BSA 2018 Soil (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(32, 'BSA_2018_SOIL_MPSP', 1, 'BSA 2018 Soil (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(34, 'BSA_2018_ASYS_MPSP', 1, 'BSA 2018 Agricultural System (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(49, 'BACA_2018_WRITING', 4, 'BACA 2018 Writing', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(118, 'BSAAE_2018_PEFM_TH', 17, 'BSAAE 2018 Production Economics and Farm Management Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(120, 'BSAAE_2018_AMP_TH', 17, 'BSAAE 2018 Agricultural Marketing and Prices Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(121, 'BSAAE_2018_AMP_MP', 17, 'BSAAE 2018 Agricultural Marketing and Prices Major Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(123, 'BSAAE_2018_RFC_MP', 17, 'BSAAE 2018 Rural Finance and Cooperatives Major Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(125, 'BSAAE_2018_NRE_MP', 17, 'BSAAE 2018 Natural Resource Economics Major Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(127, 'BSAAE_2018_FNE_MP', 17, 'BSAAE 2018 Food and Nutrition Economics Major Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(129, 'BSABME_2018_AGRI_ENTRE', 18, 'BSABME 2018 AgriculturaI Entrepreneurship', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(132, 'BSF_2018_ENVIRONMENTAL FORESTRY', 25, 'BSF 2018 Environmental Forestry', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(134, 'BSF_2018_SOCIAL FORESTRY AND AGROFOR', 25, 'BSF 2018 Social Forestry and Agroforestry', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(138, 'BSHE_2018_HUMAN AND FAMILY DEVELOPME', 26, 'BSHE 2018 Human and Family Development', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(36, 'BSA_2018_LAF_MPSP', 1, 'BSA 2018 Landscape Agroforestry (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(39, 'BSABT_2018_CRPPROTBIO_THPR', 2, 'BSABT 2018 Crop Protection Biotechnology (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(41, 'BSABT_2018_ANBIO_THPR', 2, 'BSABT 2018 Animal Biotechnology (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(43, 'BSABT_2018_FOODBIO_THPR', 2, 'BSABT 2018 Food Biotechnology (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(44, 'BSABT_2018_FOODBIO_MPSP', 2, 'BSABT 2018 Food Biotechnology (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(50, 'BAPHLO_2018_THESIS', 5, 'BAPHLO 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(51, 'BAPHLO_2018_SP', 5, 'BAPHLO 2018 Special Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(53, 'BASOC_2018_PRACTICUM', 6, 'BASOC 2018 Practicum', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(54, 'BSAM_2018_THESIS', 7, 'BSAM 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(56, 'BSAP_2018_THESIS', 8, 'BSAP 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(57, 'BSAP_2018_SP', 8, 'BSAP 2018 Special Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(59, 'BSBIO_2018_ECOLOGY', 9, 'BSBIO 2018 Ecology', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(60, 'BSBIO_2018_GENETICS', 9, 'BSBIO 2018 Genetics', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(61, 'BSBIO_2018_MICROBIOLOGY', 9, 'BSBIO 2018 Microbiology', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(63, 'BSBIO_2018_SYSTEMATICS', 9, 'BSBIO 2018 Systematics', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(64, 'BSBIO_2018_WILDLIFE_BIOLOGY', 9, 'BSBIO 2018 Wildlife Biology', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(66, 'BSCS_2018_THESIS', 11, 'BSCS 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(67, 'BSCS_2018_PRACTICUM', 11, 'BSCS 2018 Practicum', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(69, 'BSMATH_2018_SP', 12, 'BSMATH 2018 Special Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(70, 'BSAC_2018', 15, 'BSAC 2018', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(71, 'BSAC_2020', 15, 'BSAC 2020', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(73, 'BSCHEM_2020', 10, 'BSCHEM 2020', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(156, 'BSABE_2018_IABE_GENERAL', 20, 'BSABE 2018 Agricultural, Food and Bioprocess Engineering General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(155, 'BSABE_2018_AMPE_GENERAL', 20, 'BSABE 2018 Agribiosystems Machinery Power Engineering General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL),
(74, 'BSMST_2018_BIO', 13, 'BSMST 2018 Biology', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(76, 'BSMST_2018_MATH', 13, 'BSMST 2018 Mathematics', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(77, 'BSMST_2018_PHYS', 13, 'BSMST 2018 Physics', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(78, 'BSSTAT_2018', 14, 'BSSTAT 2018', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(88, 'BSABE_2018_AFBE_ENGINEERING_INDUSTRY_RESEARCH', 20, 'BSABE 2018 Agricultural, Food and Bioprocess Engineering Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(83, 'BSABE_2018_AMPE_THESIS', 20, 'BSABE 2018 Agribiosystems Machinery Power Engineering Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(86, 'BSABE_2018_AFBE_THESIS', 20, 'BSABE 2018 Agricultural, Food and Bioprocess Engineering Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(89, 'BSABE_2018_LWRE_THESIS', 20, 'BSABE 2018 Land and Water Resources Engineering Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(93, 'BSCE_2018_INNOVATIONEERING', 22, 'BSCE 2018 Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(97, 'BSChE_2018_SUGAR_TECHNOLOGY_THESIS', 21, 'BSChE 2018 Sugar Technology Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(98, 'BSChE_2018_SUGAR_TECHNOLOGY_INNOVATIONEERING', 21, 'BSChE 2018 Sugar Technology Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(100, 'BSChE_2018_PULP_AND_PAPER_THESIS', 21, 'BSChE 2018 Pulp and Paper Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(105, 'BSEE_2018_POWER_ENGINEERING_INDUSTRY_RESEARCH', 23, 'BSEE 2018 Power Engineering Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(103, 'BSEE_2018_POWER_THESIS', 23, 'BSEE 2018 Power Engineering Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(106, 'BSEE_2018_COMPUTER_ENGINEERING_THESIS', 23, 'BSEE 2018 Computer Engineering Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(110, 'BSEE_2018_ELECTRONICS_ENGINEERING_INNOVATIONEERING', 23, 'BSEE 2018 Electronics Engineering Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(82, 'BSABE_2018_ABSEE_ENGINEERING_INDUSTRY_RESEARCH', 20, 'BSABE 2018 Agrometeorology, Bio-Structures, and Environment Engineering Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(113, 'BSIE_2018_INNOVATIONEERING', 24, 'BSIE 2018 Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(114, 'BSIE_2018_ENGINEERING_INDUSTRY_RESEARCH', 24, 'BSIE 2018 Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(115, 'BSME_2018_THESIS', 29, 'BSME 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(117, 'BSME_2018_ENGINEERING_INDUSTRY_RESEARCH', 29, 'BSME 2018 Engineering Industry Research', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(119, 'BSAAE_2018_PEFM_MP', 17, 'BSAAE 2018 Production Economics and Farm Management Major Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(3, 'BSA_2018_AGR_PLNT_BRDNG_THPR', 1, 'BSA 2018 Agriculture Plant Breeding Breeding (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(5, 'BSA_2018_AGR_SEED_SCI_TECH_THPR', 1, 'BSA 2018 Agriculture Seed Science Technology (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(6, 'BSA_2018_AGR_PLNT_BRDNG_MPSP', 1, 'BSA 2018 Agriculture Plant Breeding Breeding (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(8, 'BSA_2018_AGR_SEED_SCI_TECH_MPSP', 1, 'BSA 2018 Agriculture Seed Science Technology (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(11, 'BSA_2018_HORT_CPM_ORN_THPR', 1, 'BSA 2018 Horticulture Crop Production Management Ornamentals (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(12, 'BSA_2018_HORT_CPM_FRUITS_THPR', 1, 'BSA 2018 Horticulture Crop Production Management Fruits (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(15, 'BSA_2018_HORT_PB_THPR', 1, 'BSA 2018 Horticulture Plant Breeding (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(17, 'BSA_2018_HORT_CPM_VEG_MPSP', 1, 'BSA 2018 Horticulture Crop Production Management Vegtables (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(18, 'BSA_2018_HORT_CPM_ORN_MPSP', 1, 'BSA 2018 Horticulture Crop Production Management Ornamentals (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(21, 'SHEET 12', 1, 'BSA 2018 Horticulture Physiology Tissue Culture (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(22, 'BSA_2018_HORT_PB_MPSP', 1, 'BSA 2018 Horticulture Plant Breeding (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(25, 'BSA_2018_PPTH_THPR', 1, 'BSA 2018 Plant Pathology (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(27, 'BSA_2018_WEEDS_THPR', 1, 'BSA 2018 Weeds (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(29, 'BSA_2018_AERS_THPR', 1, 'BSA 2018 Agricultural Extension (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(30, 'BSA_2018_AERS_MPSP', 1, 'BSA 2018 Agricultural Extension (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(33, 'BSA_2018_ASYS_THPR', 1, 'BSA 2018 Agricultural System (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(35, 'BSA_2018_LAF_THPR', 1, 'BSA 2018 Landscape Agroforestry (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(37, 'BSABT_2018_CROPBIO_THPR', 2, 'BSABT 2018 Crop/Plant Biotechnology (Thesis/Practicum)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(38, 'BSABT_2018_CROPBIO_MPSP', 2, 'BSABT 2018 Crop/Plant Biotechnology (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(40, 'BSABT_2018_CRPPROTBIO_MPSP', 2, 'BSABT 2018 Crop Protection Biotechnology (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(42, 'BSABT_2018_ANBIO_MPSP', 2, 'BSABT 2018 Animal Biotechnology (Major Problem/Special Problem)', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(46, 'BSFT_2018_PRSP', 3, 'BSFT 2018 PRSP', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(45, 'BSFST_2018_THPR', 3, 'BSFST 2018 THPR', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(52, 'BASOC_2018_THESIS', 6, 'BASOC 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(55, 'BSAM_2018_SP', 7, 'BSAM 2018 Special Problem', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(58, 'BSBIO_2018_CELL_AND_MOLECULAR_BIOLOG', 9, 'BSBIO 2018 Cell and Molecular Biology', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(62, 'BSBIO_2018_PLANT BIOLOGY', 9, 'BSBIO 2018 Plant Biology', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(65, 'BSBIO_2018_ZOOLOGY', 9, 'BSBIO 2018 Zoology', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(68, 'BSMATH_2018_THESIS', 12, 'BSMATH 2018 Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(72, 'BSCHEM_2018', 10, 'BSCHEM 2018', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(75, 'BSMST_2018_CHEM', 13, 'BSMST 2018 Chemistry', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(79, 'BSDC_2018', 16, 'BSDC 2018', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(80, 'BSABE_2018_ABSEE_THESIS', 20, 'BSABE 2018 Agrometeorology, Bio-Structures, and Environment Engineering Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(81, 'BSABE_2018_ABSEE_INNOVATIONEERING', 20, 'BSABE 2018 Agrometeorology, Bio-Structures, and Environment Engineering Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(84, 'BSABE_2018_AMPE_INNOVATIONEERING', 20, 'BSABE 2018 Agribiosystems Machinery Power Engineering Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(87, 'BSABE_2018_AFBE_INNOVATIONEERING', 20, 'BSABE 2018 Agricultural, Food and Bioprocess Engineering Innovationeering', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(122, 'BSAAE_2018_RFC_TH', 17, 'BSAAE 2018 Rural Finance and Cooperatives Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(124, 'BSAAE_2018_NRE_TH', 17, 'BSAAE 2018 Natural Resource Economics Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(126, 'BSAAE_2018_FNE_TH', 17, 'BSAAE 2018 Food and Nutrition Economics Thesis', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(128, 'BSABME_2018_AGRI_MGMT', 18, 'BSABME 2018 AgriculturaI Management', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(130, 'BSECON_2018_DEVELOPMENT_ECON', 19, 'BSECON 2018 Development Economics', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(131, 'BSECON_2018_ENVRMENTAL_ECON', 19, 'BSECON 2018 Environmental Economics', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(133, 'BSF_2018_PRODUCTION AND INDUSTRIAL F', 25, 'BSF 2018 Production and Industrial Forestry', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(135, 'CIF_2018', 30, 'CIF 2018', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(136, 'BSHE_2018_HUMAN SETTLEMENTS PLANNING', 26, 'BSHE 2018 Human Settlements Planning', NULL, 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(144, 'BACA_2018_GENERAL', 4, 'BACA 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(145, 'BAPHLO_2018_GENERAL', 5, 'BAPHLO 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(147, 'BSAM_2018_GENERAL', 7, 'BSAM 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(148, 'BSAP_2018_GENERAL', 8, 'BSAP 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(150, 'BSCS_2018_GENERAL', 11, 'BSCS 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(151, 'BSMATH_2018_GENERAL', 12, 'BSMATH 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(153, 'BSMST_2018_GENERAL', 13, 'BSMST 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(158, 'BSCE_2018_GENERAL', 22, 'BSCE 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(165, 'BSIE_2018_GENERAL', 24, 'BSIE 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(166, 'BSME_2018_GENERAL', 29, 'BSME 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(167, 'BSAAE_2018_GENERAL', 17, 'BSAAE 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(169, 'BSECON_2018_GENERAL', 19, 'BSECON 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(170, 'BSF_2018_GENERAL', 25, 'BSF 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(168, 'BSABME_2018_GENERAL', 18, 'BSABME 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(171, 'BSHE_2018_GENERAL', 26, 'BSHE 2018 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(172, 'BSAcc_2022_GENERAL', 173, 'BSAcc 2022 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(173, 'AAEntrep_2022_GENERAL', 174, 'AAEntrep 2022 General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(96, 'BSChE_2018_GENERAL_ENGINEERING_INDUSTRY_RESEARCH', 21, 'BSChE 2018 General Engineering Industry Research', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(164, 'BSEE_2018_ELECTRICAL_GENERAL', 23, 'Bachelor of Science in Electrical Engineering', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'true', NULL, NULL, NULL),
(154, 'BSABE_2018_ABSEE_GENERAL', 20, 'BSABE 2018 Agrometeorology, Bio-Structures, and Environment Engineering General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL),
(157, 'BSABE_2018_LWRE_GENERAL', 20, 'BSABE 2018 Land and Water Resources General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL),
(161, 'BSCHE_2018_PPT_GENERAL', 21, 'BSCHE 2018 Pulp and Paper Technology Track General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL),
(160, 'BSCHE_2018_SUTC_GENERAL', 21, 'BSCHE 2018 Sugar Technology Track General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL),
(163, 'BSEE_2018_COMPUTER_ENGG_GENERAL', 23, 'BSEE 2018 Computer Engineering General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL),
(162, 'BSEE_2018_POWER_ENGG_GENERAL', 23, 'BSEE 2018 Power Engineering General', 'GENERAL', 'ACTIVE', NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL),
(180, 'BSMatE_2022', 369, 'BSMatE General 2022', 'GENERAL', 'ACTIVE', 'LBDENSC', 'CEAT', '2024-07-15 00:56:10', '2024-07-15 00:56:10', 'TRUE', NULL, NULL, NULL);